# general
result_dir: ./result
verbose: True
parallel: False

# task
tasks:
  - semseg
num_classes: 10

# dataset
dataset_dir: ../datasets/DEM_NZ
rgb_only: True
mean:
  - 0.0357015
  - 0.05297579
  - 0.05113702
  - 420.23532
  - 4.96576484
  - 1.00909591
std:
  - 0.02163442
  - 0.02770515
  - 0.03341371
  - 267.00613
  - 5.874813
  - 0.05473682

# split
train_set_name:
  - Christchurch_Kaiapoi
  - Kaikoura_Marlborough
test_set_name:
  - Christchurch_Akaroa

# resample info
resolution: 7.5
sample_size: 300
sample_scale: 10

# model
model_name: deeplabv3_resnet50
init_random: False

# optimizer
optimizer: SGD
# optimizer: Adam
scheduler: ConstantLR
# scheduler: OneCycleLR

# training
batch_size: 40
epochs: 10
lr: 0.01
